baseURL = "/"
languageCode = "en-us"
title = "Sarvesh Raj"
theme = "novela"

[taxonomies]
year = "years"
tag = "tags"
author = "authors"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 2
