version: 2.1
jobs:
	  build:
	    docker:
	      - image: cibuilds/hugo:0.69
	    steps:
	      - checkout
        - run: git submodule sync && git submodule update --init
	      - run:
	          name: "Build Website with Hugo"
	          command: HUGO_ENV=production hugo -v -s
	      - run:
	          name: "Test The Website"
	          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
	      